### ISSUE TITLE
Custom sounds

### ISSUE THREAD

**Issue by lulon45** [leminlimez/Cowabunga#108]
I can’t import any custom sounds on the new release, it launches my files i can see the mp3 files but cant select it
![Uploading 60E04ECB-A9EA-457A-8668-7DA5097112B8.png…]()

**Comment by lulon45** [comment]
When i just copy the mp3 files to cowabunga_audio when i select the sound in cowabunga it says failed to Apply audio

**Comment by leminlimez** [comment]
esign does not correctly sign entitlements, please use altstore or sideloadly
