### ISSUE TITLE
Cowabunga crashes when trying to change device SubType (iPhone X gestures)

### ISSUE THREAD

**Issue by zLoy64** [leminlimez/Cowabunga#114]
iPhone 7 Plus, iOS 15.6 unjailbroken.

I'm using the newest version of Cowabunga, but I also tried with the beta. When I tap on "iPhone X Gestures (2436)" the app crashes and it doesn't work. I tried to manually change the value in the _com.apple.MobileGestalt.plist_ with Filza and Santander, but the file seems to be missing when I go to `/var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches/`.

I tried to enable X gestures with TrollBox, but it gives me this error:
![IMG_7883](https://user-images.githubusercontent.com/77848524/218267241-91cb7e15-a7e8-48a8-96d8-2351628520a3.jpg)

**Comment by leminlimez** [comment]
no idea how that happens but i cant fix it if theres no file

**Comment by zLoy64** [comment]
Ok thanks for letting me know, I think i will probably jailbreak it if that's the only way (besides restoring the device, but I want to keep the iOS version).

**Comment by zLoy64** [comment]
> no idea how that happens but i cant fix it if theres no file

Ok thanks for letting me know, I think i will probably jailbreak it if that's the only way (besides restoring the device, but I want to keep the iOS version).
