### ISSUE TITLE
[Issue] Applied icons have severe compression artifacts

### ISSUE THREAD

**Issue by cassafrass387** [leminlimez/Cowabunga#116]
Running the latest (as of 12:11 CST) build of Cowabunga on an iPhone 13 running 16.0. Everything applies fine, but the icons themselves have bad compression artifacts. Here are a couple of examples:
![F3C18B2D-4947-41F6-9392-35BB0BF29889](https://user-images.githubusercontent.com/16978149/218274427-9ed2461f-642a-4f14-be7d-c9e5357e8af0.jpeg)
On this one, the Snapchat icon is really obviously compressed. Facetime looks fine though.
![8A0E885E-8C30-4941-956B-3FFD16FD94E2](https://user-images.githubusercontent.com/16978149/218274482-e720e16b-f5d1-47a8-9bfd-0ab357486a2b.jpeg)
News icon has some mild artifacts, nothing else here is themed.
![ECD62A83-00F2-4ADF-BC41-0A99F56E7496](https://user-images.githubusercontent.com/16978149/218274521-331298c4-d58f-4d76-960e-697778074a1e.jpeg)
Here, Voice Memos, Calculator, Google, all have artifacts, App Store, and a few others are fine though.
I’m using the KindaStock icon pack for testing right now but if you’d like me to try with something else please let me know.

**Comment by leminlimez** [comment]
we cannot fix this, it is a limitation of mdc

**Comment by cassafrass387** [comment]
Damn, okay. Thanks for letting me know.

**Comment by leminlimez** [comment]
i was wrong, it is possible but we need to change our algorithm, so it will come at a later date

**Comment by BomberFish** [comment]
This will be fixed in a future update.
