### ISSUE TITLE
[Feature Request] AOD on unsupported OLED devices

### ISSUE THREAD

**Issue by salocor** [leminlimez/Cowabunga#12]
Not sure if this is possible but it would be super cool. There may be a plist somewhere that would enable it.

**Comment by leminlimez** [comment]
I do not have an ios 16 device so there is no way I could test it

**Comment by salocor** [comment]
Gotcha. I have a 12 pro on iOS 16.1.2. If you ever need me to test something for ya i'd be more than happy. I can send you my Discord if you'd like.

**Comment by leminlimez** [comment]
Not possible as unsupported devices can't go to 1 Hz so the phone will most likely panic
