### ISSUE TITLE
Not able to import any theme into cowabunga.

### ISSUE THREAD

**Issue by m4l1k64** [leminlimez/Cowabunga#127]
Downloaded the theme from the discord server, unzipped it in the files and then tried to import it from cowabunga app but it doesn’t do anything when go the theme folder and tap open. Screenshot attached.
![A41A643D-3FB8-4D78-855A-D8DEFAC5367D](https://user-images.githubusercontent.com/115430485/218299769-874df054-0827-46e9-8c08-8e7016fe92c1.png)

**Comment by a1660658831** [comment]
Me too.

**Comment by Nigel1992** [comment]
If "Open" doesn't work, you'll need a different sideloading tool/method.

**Comment by leminlimez** [comment]
you need to use a different signing service
ones like esign dont sign entitlements properly, i cannot fix this
