### ISSUE TITLE
Only Home and Tools buttons?😳 iphone 12 ios 14.8.1 installed via Trollstore.

### ISSUE THREAD

**Issue by sirbinh88** [leminlimez/Cowabunga#128]
![image](https://user-images.githubusercontent.com/116496221/218302278-dabe331e-3b79-468a-82d1-32bf09830bd8.png)

**Comment by leminlimez** [comment]
themes and explore aren't available on ios 14

**Comment by potteredgerton** [comment]
@leminlimez why not, mdc exitsed then
