### ISSUE TITLE
[Fixed] [Bug] Disable folder background & App switcher blur didn't work

### ISSUE THREAD

**Issue by kleqing** [leminlimez/Cowabunga#129]
I had turned on 'disable folder background' and 'disable app switcher blur' but seem like it didn't working even I press fix tweak and respring. I don't know why but maybe the issues only happened on my home screen. I can adjust everything else on lock screen and status bar.

iPhone 11 - iOS 16.1.2

![image](https://user-images.githubusercontent.com/78801337/218310135-5f1352ee-6b0d-4e30-86f0-201cd91a2b40.png)

![image](https://user-images.githubusercontent.com/78801337/218310144-f17033e3-027d-4558-b226-d7e89f59d6ac.png)

**Comment by Nigel1992** [comment]
I have the same issue running on 16.1.2 aswell.
When you hit Apply, simply use the respring glitch and applying a tweak should work all the time.
See https://www.reddit.com/r/jailbreak/comments/107pr7w/tutorial_app_library_respring_method_for_ios_16/

**Comment by tvcbuv** [comment]
also,i found that the hide dock will not work after 3min from the widgets page back to the home screen,but within the cowabunga app it shows selected

**Comment by kleqing** [comment]
@Nigel1992 I kew this method before and I had tried on my iPhone, still not working. Also idk why but this method only work in iOS 16.1

**Comment by kleqing** [comment]
@tvcbuv  Yeah, even i pressed Fix Tweaks, it doesn't work.

**Comment by Nigel1992** [comment]
> or 

Did it actually respring after doing the glitch ?

**Comment by kleqing** [comment]
> > @Nigel1992 I kew this method before and I had tried on my iPhone, still not working. Also idk why but this method only work in iOS 16.1 or lower
> 
> > Did it actually respring after doing the glitch
>
> No. even respring using instaspring or santanderEscapse didn't work.

**Comment by kleqing** [comment]
[Fixed]

So, I've found a way to make the tweak work! But it have a little tricky. Just make sure you turned 'Run in background' on and changed 'Background update frequency' to 'Frequent'

![image](https://user-images.gitthubusercontent.com/78801337/218363337-cf914707-a8f0-40b6-9e0e-da2da6f34f24.png)

Sometime the tweak would cause a bug (like you enable both disable dock background and folder background on but it only hidden dock backgound). Here's how to fix:

1. Open app and press fix tweak. Then make sure  'Run in background' on, also make sure 'Background update frequency' was set to 'Frequent'. Then you have to respring first (using respring button in the app)
2. After respring, open Cowabunga again, and do the same things again but at this time don't touch 'Run in background'
3. Choose your tweaks that you want to apply and press apply button.
4. After that, respring your phone again using the respring button on main page. And enjoy!

![image](https://user-images.githubusercontent.com/78801337/218363996-9ff2f38e-a9d4-4bd1-be6b-d61faeeb397b.png)
![image](https://user-images.githubusercontent.com/78801337/218364009-6eb92386-a1e6-41cd-ba68-9e40fa6eb7ee.png)![image](https://user-images.githubusercontent.com/78801337/218364017-9ecd02a9-dcf7-4659-a872-e0db7ba724cd.png)
![image](https://user-images.githubusercontent.com/78801337/218364195-86f3ed41-3d20-4da2-b0c6-115c76769b97.png)
