### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by wes1993** [leminlimez/Cowabunga#13]
Hello,
Thanks a lot for your wonderful works, could you add also the Dynamic Island (DynamicCow) and don’t change?

Thanks a lot
Stefano

**Comment by leminlimez** [comment]
potentially but I do not have an ios 16 device so I would not be able to test it

**Comment by wes1993** [comment]
If you want I can test for you, if you can send me the IPA with this fuctionality

**Comment by leminlimez** [comment]
I will add it to the next update but it will only be visible on ios 16 and will be untested. I will follow how DynamicCow does it so it should work in theory.

**Comment by wes1993** [comment]
In perfect!! Thanks a lot I will keep you updated :)

**Comment by leminlimez** [comment]
It is in the latest update

**Comment by wes1993** [comment]
I have downloaded the latest version and i can confirm that the DynamicIsland works with iPhone 13 Pro Max iOS 16.1.2.

Now the last mod if you can add is the font change :-D

Best Regards
Stefano

**Comment by leminlimez** [comment]
create a new issue so i remember
