### ISSUE TITLE
Black Screen After Changing Screen Resolution

### ISSUE THREAD

**Issue by Mjevia** [leminlimez/Cowabunga#137]
I tried to change my screen resolution but it respringed but its all Black screen so i restarted my phone but when i tried to do it again its just all black screen so i tried to uninstalling it and downloading it again to see if it will fix the problem but still black screen i know that you have worked so hard for these to work so I hope that you can fix this that’s all thanks

**Comment by BomberFish** [comment]
Force reboot your phone.

**Comment by pazza2234** [comment]
you will need to do a force reboot. To force reboot please Press vol up, release vol up, press vol down, release vol down, then hold lock/power button for a wile.
