### ISSUE TITLE
Phone not opening up and Bootlooped

### ISSUE THREAD

**Issue by AveR4g3** [leminlimez/Cowabunga#138]
iPhone 8, iOS 15.3.1

This is most likely my fault, but when I wanted to see what would happen if I set the custom size to a passcode button to 2500 x 2500 (a dumb mistake) my iPhone kept respringing and crashed whenever I tried to open the phone. I then proceeded to try and force restart it, but then it ended up bootlooping (it went on for hours). In the end, I had to upgrade to ios 16.3 with iTunes. 

I would be looking towards for ways to get back to iOS 15 without having to factory reset. Although, I am pretty sure that it is not possible. I do have the .ipsw and shsh2 blobs for iOS 15.4.1 and access to both windows and linux computers. I just need to find a way to set nonce.

Thank you in advance, and I repeat, this was my mistake, stay safe.

Cowabunga version 7.0.4 if this is in the wrong spot, which I think it is in

Edit: Actually, no, I just remembered that it was only when I reseted the passcode faces after it, not when I set the size.

**Comment by BomberFish** [comment]
You can downgrade to iOS 15.6 RC

**Comment by AveR4g3** [comment]
> You can downgrade to iOS 15.6 RC. 

Thank you, I in fact, am aware of this, but do you know any way to do it without erasing data, I am pretty sure that you can not, but I am asking for confirmation

**Comment by c22dev** [comment]
You can't without erasing.

**Comment by AveR4g3** [comment]
> You can't without erasing.

Thank you!

**Comment by AveR4g3** [comment]
> You can downgrade to iOS 15.6 RC. 

Back on with palera1n (actually the first time using checkm8 jailbreak). Always preferred semi-tehered.

**Comment by potteredgerton** [comment]
L

**Comment by BigBoiMan123** [comment]
You can follow https://gist.github.com/0xallie/aac55c97f7925cddcf5ec3167f85dfe8 to set your nonce and restore to 15.4.1 with blobs.
