### ISSUE TITLE
[Feature Request] Remove the search button on the homescreen

### ISSUE THREAD

**Issue by mmmmmabil** [leminlimez/Cowabunga#14]
if possible add a toggle for removing the search button above the dock on the homescreen 
![image](https://user-images.githubusercontent.com/95183826/211711195-07722396-80cf-4d69-83b8-cce57b5be237.png)

**Comment by leminlimez** [comment]
I do not have an ios 16 device so I won't be able to search for it in the file system

**Comment by Radiicall** [comment]
@leminlimez if you give some pointers on how to search through the filesystem and where I could find this then I could try

**Comment by leminlimez** [comment]
It's probably somewhere in /System/Library/PrivateFrameworks but idk where

**Comment by Radiicall** [comment]
What can I use to look through the FS?

**Comment by leminlimez** [comment]
santander macdirtycow, but you need to use the "go" button to go to /System/Library

**Comment by Radiicall** [comment]
Do you have an ipa i can use?

**Comment by PinguPJ** [comment]
https://www.macrumors.com/how-to/remove-home-screen-search-button/

**Comment by leminlimez** [comment]
since its a default option, i'm going to go ahead and close this
