### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Pogchamp2000** [leminlimez/Cowabunga#141]
Saved themes not changing passcode buttons on ios 16.0.2 (iPhone XR )

**Comment by pazza2234** [comment]
Have you tryed going to tools -> passcode faces?

**Comment by Pogchamp2000** [comment]
> Have you tryed going to tools -> passcode faces?

Yes, I have it was a bug in an older version of this app.

**Comment by Pogchamp2000** [comment]
> > Have you tryed going to tools -> passcode faces?
> 
> Yes, I have it was a bug in an older version of this app.

The bug was patched tho
