### ISSUE TITLE
Unable to sideloaf through scarlet 

### ISSUE THREAD

**Issue by dev-095** [leminlimez/Cowabunga#142]
Could you please help, I’m unable to install and there is this error which i can’t understand 
![404C66E0-C506-421E-A5F2-0132B4890305](https://user-images.githubusercontent.com/125238281/218373060-6b804b15-1a68-49b1-aa89-bef5faacd826.png)

**Comment by c22dev** [comment]
Scarlet issue, try again or check if your connected to the internet. Btw, scarlet is not recommended to use with Cowabunga. You could try using SideStore or AltStore and this would also fix your issue

**Comment by potteredgerton** [comment]
this is because scarlet is not signed currently. https://zeus.me is signed, but it is better to manually sideload with altstore or sideloadly as enterprise certs are risky
