### ISSUE TITLE
Some apple’s icon can‘t be changed

### ISSUE THREAD

**Issue by vance808** [leminlimez/Cowabunga#144]
My theme can be displayed, which is great, but some Apple app's icons cannot be changed, I want to know the reason, thank you

**Comment by mohammedalkhldiy** [comment]
Just like you, File and YouTube always appear in low resolution


![E772DEF9-2758-4FE7-9AD8-B61E7E4BFE22](https://user-images.githubusercontent.com/90659707/218492480-8d2d4b54-a49f-42bc-bbf4-b64ee5457717.jpeg)

**Comment by c22dev** [comment]
That is normal as the file can't exceed original icon size. Files and YouTube icon are such apps. Try using a shortcut

**Comment by mohammedalkhldiy** [comment]
@c22dev 

how can you help me?  With all the themes I have the same problem

Watch no matter how hard you try to change the theme, the problem is the same

![image](https://user-images.githubusercontent.com/90659707/218755520-ce5d98e8-1694-462d-8077-643a58b31f73.png)

**Comment by leminlimez** [comment]
many of apple's icons have issues applying, and we cannot make calender or clock work

**Comment by leminlimez** [comment]
you may need to try applying multiple times

**Comment by mohammedalkhldiy** [comment]
@leminlimez 
I only have a problem with the YouTube icon and file manager appearing in low resolution
