### ISSUE TITLE
App still crashes on launch.

### ISSUE THREAD

**Issue by Bigro82** [leminlimez/Cowabunga#152]
Please update to fix the issue of app crashing on launch. On iPhone XS iOS 16.1.2

**Comment by leminlimez** [comment]
i cant debug to figure out whats causing it, this is very hard to fix

**Comment by Bigro82** [comment]
Sigh 😖😖😖😖Sent from my iPhoneOn Feb 15, 2023, at 10:33 PM, leminlimez ***@***.***> wrote:﻿
i cant debug to figure out whats causing it, this is very hard to fix
