### ISSUE TITLE
Audio change with Cowabunga not working with my SE 1st gen (Trollstore, iOS 15.1)

### ISSUE THREAD

**Issue by drcs68** [leminlimez/Cowabunga#160]
I've been trying with every release since Cowabunga versions 7.x, and still with 8.0.3 and 8.0.4 beta it's not working.

The app doesn't give me an error, on the contrary, when I click apply it says the changes were successfully made, and then it says to respring. I do a respring, reboot, nothing is working.

**Comment by leminlimez** [comment]
respring should work but reboot will revert
what are u trying to change?

**Comment by drcs68** [comment]
Unfortunately it's not working with respringing :/ 
I am trying to change charging sound to old charging and lock sound to old lock.

**Comment by jkrosado** [comment]
same issue, i tried all keyboard sounds and the charge sound to no avail. i'm using an iphone 14 pro on 16.0.3.
