### ISSUE TITLE
[Bug] None of the 3 keyboard sounds apply

### ISSUE THREAD

**Issue by unChiled** [leminlimez/Cowabunga#161]
The title says it all. Not even the included piano sound does. It's been like this since 7.x I believe? 

Device Info: 
iPhone 8 Plus
iOS 16.1.2

**Comment by AdverseMiller** [comment]
Right with you, having same issue on ip12 15.6

**Comment by Aftended** [comment]
iPhone 13 pro max 15.0.2 too.
— (Maybe Message’s app), sounds works without problem’s, mb. 

After locking my 📱, sound  
Windows XP 🔒— works fine (rarely), 
usually glitchy, sound plays (~0.8sec like). Let’s see after new update.

**Comment by Aftended** [comment]
> Fixed in v8.1.0 🎉

Still not, sounds keyboard OK!TY!

Sometimes (usually or always), when i put lock - **Windows XP sound** = **0.5sec** or for real is not working at the moment. 

To **fix**: Respring couple time's to make sounds working... not for a long time as well. 

Fonts: I chosen from google fonts 
(i downloaded, renamed), anyway it's not showing to me after **respring**, **rebooting** and **rejailbreaking** with same process = no )':
