### ISSUE TITLE
Perhaps WhiteList is not for anti-revoke

### ISSUE THREAD

**Issue by miyuanbo** [leminlimez/Cowabunga#162]
According to descriptions of the WhiteList app, it only unblocks 'enterprise' apps, and it doesn't say 'personal' sideloaded apps.
I did a test myself last week, leaving a single sideloaded app A to revoke while keeping WhiteList app refreshed daily. 
After 8 days, app A expires (showing 'is no longer available'), and applying WhiteList overwritting does not make app A available again.

**Comment by leminlimez** [comment]
expiration ≠ revoke
