### ISSUE TITLE
Unable to apply saved passcode faces

### ISSUE THREAD

**Issue by miyuanbo** [leminlimez/Cowabunga#163]
Selecting saved passcode face themes has no effect in 8.0.4.
![FB9557DE-D362-4A77-94A1-0A1E391665F7](https://user-images.githubusercontent.com/6468993/219939028-15af583b-438d-4ad3-b2a7-ddf3cc85b664.jpeg)

**Comment by leminlimez** [comment]
I will look into this, it is possibly caused by an issue with the name of the folder
