### ISSUE TITLE
Lock Icon & SpringBoard Colors (conflict)

### ISSUE THREAD

**Issue by PaoCaro** [leminlimez/Cowabunga#165]
So, when I change anything from "SpringBoard Color" (for example: Dock color), after respring, if I try to change the lock icon and respring, any change made in SpringBoard will reset to default

**And vice versa** (Lock Icon and then "SpringBoard Color", the lock icon will reset to default)

Besides that, **thank you** so much for your amazing effort on this
I really admire you guys :))

**Comment by leminlimez** [comment]
I recommend turning on "run in background" as it will work to keep everything applied
