### ISSUE TITLE
Lock icons not appearing. importing audio not working and more...

### ISSUE THREAD

**Issue by Xboy3998** [leminlimez/Cowabunga#167]
The lock icons just simply don't appear on the Lock Screen. The importing for audio also just doesn't work. When I click a sound (wav or mp3) then it just doesn't open it in cowabunga. Also, maybe add custom badges like TrollTools. That would be epic

**Comment by leminlimez** [comment]
custom badges are already in but only for ios 14-15

**Comment by Xboy3998** [comment]
> custom badges are already in but only for ios 14-15

Okay
