### ISSUE TITLE
red bar when enable gestureX

### ISSUE THREAD

**Issue by latiefahmad** [leminlimez/Cowabunga#17]
I got this when enable gestureX, can you fix it?
![Uploading E2F9F9B6-72E1-4BE5-AFA3-371CF4138FD3.png…]()

**Comment by leminlimez** [comment]
device?

**Comment by leminlimez** [comment]
could you tell me the number next to the default in the menu?

**Comment by leminlimez** [comment]
This is more difficult than I thought. I thought I knew the issue but this is something different. I will keep looking.

Can you send a screenshot of the red bar? (if you already sent it I can't see it)

**Comment by leminlimez** [comment]
Do the gestures work at all despite the red bar?

**Comment by leminlimez** [comment]
This is an ios 16 issue I believe but regardless there is no way for me to fix it
