### ISSUE TITLE
Software Version Spoof not working.

### ISSUE THREAD

**Issue by TherionRO** [leminlimez/Cowabunga#18]
Hey! I cannot spoof the ios version using the tool provided on the miscellaneous tab. When i change the version and go into settings nothing changed,also using a third party app to show what ios version I have still nothing changes,am I missing something or the feature is not working? Device : 13 Pro max , Real ios version : 16.1 Stable/release

**Comment by TherionRO** [comment]
Update : I tried editing the build version from the plist file myself using santander and I get this error : Error occurred: Root helper unavailable? Even tho root helper is enabled. Using another dirtycow file explorer,after changing the plist it gets changed but after restarting the app the plist reverts back.

**Comment by leminlimez** [comment]
You have to modify it to something that is the same length or less like 16.9 instead of 16.1

**Comment by TherionRO** [comment]
Yes,i already tried that but it is still not working

**Comment by TherionRO** [comment]
Update : Also tried on 14 Pro Max running 16.1.1 and XS Max running 16.0 ,non of them are working
