### ISSUE TITLE
Can’t revert Apple wallet card back

### ISSUE THREAD

**Issue by lewis0917** [leminlimez/Cowabunga#181]
I set the image to be something obscene and now I can’t change it to anything else.

**Comment by lewis0917** [comment]
Also experiencing issues with sounds not changing for charging and taking screenshots. iPhone 6s iOS 14.6

**Comment by amusingimpala75** [comment]
Not sure of this is one of those features, but I presume you read the README.md, including the section near the top that says
> Warning: Some changes are permanent on iOS 14.0-14.8.1

which could be the case here.

**Comment by lewis0917** [comment]
I managed to revert it by opening cowabunga via TrollStore rather than Home Screen. Phew
