### ISSUE TITLE
None of the tweaks apply

### ISSUE THREAD

**Issue by seropigeorgedev** [leminlimez/Cowabunga#187]
Latest, apple ipad air 2 a8x

**Comment by leminlimez** [comment]
what ios?

**Comment by seropigeorgedev** [comment]
15.0 also it says all tweaks has been applied and i respringed but it didn't work (maybe it has something to do with trolltools?)

**Comment by leminlimez** [comment]
it shouldn't, it might be better to turn off auto respring and then maybe try respringing through trolltools

**Comment by memory9421** [comment]
![c5fd5fea0c9f3b45099de32763654e7](https://user-images.githubusercontent.com/116992964/222653525-aa88344b-e1c6-4350-8d79-bebf7a5a9b50.jpg)
Can we support this theme in the future

**Comment by seropigeorgedev** [comment]
It now kinda worked but not anymore? It's weird but the first time it worked the other times it didn't and applying themes doesn't work at all

**Comment by memory9421** [comment]
It means that the theme in Cowabunga also cannot be applied in percentage

**Comment by memory9421** [comment]
This means that the theme in Cowabunga also cannot be applied 100%
