### ISSUE TITLE
Background applying include Springboard colors?

### ISSUE THREAD

**Issue by miyuanbo** [leminlimez/Cowabunga#192]
I don't see an option to enable Springboard colors for Background applying, is it a mistake or they just don't need to be applied in background?

**Comment by miyuanbo** [comment]
BTW, why not automatically apply the "fix tweaks" function for a few times on each button press?
It seems that pressing that button a lot before respring may increase the probability of successfully applying all of the tweaks.

**Comment by leminlimez** [comment]
springboard colors are included in their counterparts, ie. dock applies both hiding dock and the dock color
i am working on a better ui for springboard tools in general so this should be less confusing in a later update
