### ISSUE TITLE
Broken icon theming on 12.9 inch iPad pros

### ISSUE THREAD

**Issue by BigBoiMan123** [leminlimez/Cowabunga#194]
App icon theming is broken on 12.9 inch iPad pros. On versions prior to 8.10, everything would seem to work but the icons would not apply on the Home Screen, but they do apply in things like the app switcher and shortcuts app. On versions 8.10 and 8.1.1 icon cache seems to be broken, the process ends abruptly when applying themes and manually resetting the icon cache hangs forever.

**Comment by leminlimez** [comment]
odd, all that changed is the resetting cache function to be safer

the manually resetting cache will be fixed next update, i forgot to have it automatically respring
