### ISSUE TITLE
Screenshot doesn’t work

### ISSUE THREAD

**Issue by Mjevia** [leminlimez/Cowabunga#195]
I seem to have noticed that my screen shot doesn’t work after i Added iphone X gestures to my iphone 6 so i just use screen shot using my assistive touch but it’s pretty annoying that i have to click more options just ti fake a screen shot so pls fix this problem thank you so much

**Comment by leminlimez** [comment]
i cannot fix this

volume up + power should screenshot, but i cannot change anything more without a jailbreak
