### ISSUE TITLE
Not Working on iOS 16.0

### ISSUE THREAD

**Issue by futureflash01** [leminlimez/Cowabunga#20]
I'm running iOS 16.0 on my iPhone 11 Pro Max. I tried applying a couple patches more than 20 times (literally LOL). Unfortunately I couldn't get it to work. I tried applying a single patch more than 10 times on its own. I tried applying and respringing over and over again. I even tried to disable a patch, re-enable it, and respring, more than 3 times in a row. Nothing would work unfortunately. I mainly use a service called Signulous to side load apps, but I tried with AltStore as well and it wouldn't work. I'm not sure why. By the way, I was using the latest version of CowaBunga (v5.2.0). Any help would be appreciated, thanks :)

**Comment by TherionRO** [comment]
In also using signulous and i have the same problem. What I did to fix it,i simply respringed once without applying anything,not even one tweak from other apps so basically everything gets back to stock,and then open the app apply all the tweaks and respring. All the tweaks works for me using this method except the ios version spoof and the home bar hidder. Hope this also works for you,let me know

**Comment by Nigel1992** [comment]
For anyone having issues with the tweaks not being applied.

1. Select your tweaks.
2. Hit “Apply without Respring”
——
3. Use the below steps. (might take a few tries)

1.	⁠Go to your Home Screen and swipe all the way right to your App Library
2.	⁠Swipe down to enable list view
3.	⁠Type “A” in the search bar
4.	⁠Double tap the “A” in the search bar, it should pop up the select text highlight
5.	⁠Drag the LEFT part of the select text directly right towards the cancel option on the search bar, don’t lift your finger from that selector
6.	⁠If done correctly you’ll see a second cancel option kinda ghostly appear above the search bar, all while still holding your finger on that selector, use your other finger to hit the backspace on the keyboard to delete the “A”
7.	⁠Remove your finger when the screen goes black.

🙏 Credits to dysfunctionalvet420 on Reddit.
