### ISSUE TITLE
Redbar on dynamic island and dynamic island pro max, Iphone Xr 16.0.3

### ISSUE THREAD

**Issue by fikriardyant** [leminlimez/Cowabunga#21]
i'm on ios 16.0.3, iphone xr, and the default number is (1792)
![WhatsApp Image 2023-01-13 at 18 40 50](https://user-images.githubusercontent.com/49143335/212312331-3a168a7a-efed-4c5a-9521-b9ba878049ee.jpg)

**Comment by leminlimez** [comment]
This is a known issue on ios 16 even for dynamiccow. there is nothing i can do
