### ISSUE TITLE
can you support this function?

### ISSUE THREAD

**Issue by TzuChiangLi** [leminlimez/Cowabunga#215]
Can you forbidden longpress on the lock screen?
Long press to enter lock edit screen , can you support it ?

**Comment by TzuChiangLi** [comment]
If you understand Chinese, I will describe my problem in Chinese.
问题：
能否支持禁用锁屏界面长按进入锁屏编辑界面的功能？

**Comment by leminlimez** [comment]
not possible to change functions without jailbreak
