### ISSUE TITLE
Some apps not changing icons, Ex: Messages, Phone, Appstore (All apple included apps)

### ISSUE THREAD

**Issue by sryerabati** [leminlimez/Cowabunga#218]
I am also having the icon compression but I heard this will be fixed in a later update. Mostly just phone and messages + Appstore that aren't changing, just the apple official apps.

**Comment by leminlimez** [comment]
fixed in upcoming v10

**Comment by sryerabati** [comment]
> fixed in upcoming v10

So in v10, I will be able to change phone icon too?
