### ISSUE TITLE
Red bar at the top is distracting

### ISSUE THREAD

**Issue by ExpirealBurner** [leminlimez/Cowabunga#22]
There is a red bar at the top of the screen that is distracting when on apps like tiktok or netflix, and yes i am a maniac that preffers watching movies in a vertical orientation. but it also shows up on landscape viewing

iPhone SE Gen 2

**Comment by leminlimez** [comment]
ios 16?

**Comment by ExpirealBurner** [comment]
yes

**Comment by ExpirealBurner** [comment]
![2023_01_13_20_48_IMG_0229](https://user-images.githubusercontent.com/122629175/212374755-5a3c9830-3d79-43f7-9eb1-da3c82a9aa00.JPG)

**Comment by ExpirealBurner** [comment]
> ios 16?

16.1.2 to be exact

**Comment by leminlimez** [comment]
Known issue on ios 16 and nothing can really be done as far as i know
