### ISSUE TITLE
Device spoofing (feature request)

### ISSUE THREAD

**Issue by puffycheezball8** [leminlimez/Cowabunga#220]
### Hey leminlimez,

I was just wondering if I could spoof my device, eg iPad 8 -> iPad Pro 2022
And if so would I be able to use stage manager on it,
I have an iPad 8th gen, iOS 16.1.1

Thanks in advance, keep up the good work!

**Comment by leminlimez** [comment]
This is too risky to add, someone tried this with custom operations and it gave an activation error, forcing them to update, so I will not add it

**Comment by puffycheezball8** [comment]
Ok thanks
