### ISSUE TITLE
Only works after a free resprings, disable shortcut banner doesn’t work at all

### ISSUE THREAD

**Issue by Pacycs** [leminlimez/Cowabunga#23]
Basically the title. I am using an iPhone 12 running iOS 15.4.1

**Comment by leminlimez** [comment]
I am aware of the shortcut banner but try applying without respringing and then respring after a few seconds

**Comment by Pacycs** [comment]
Yeah, it’s not a big problem after all. But also after some time some of the folder backgrounds appear again. 
![Uploading BC6CB1FB-539F-4E53-B7E3-85169612FB90.png…]()

**Comment by Pacycs** [comment]
Yeah, it’s not a big problem after all. But also after some time some of the folder backgrounds appear again.
![Uploading 4A16067A-5142-4E00-AB50-0BD2095B5EC5.png…]()

**Comment by leminlimez** [comment]
Working on a fix for that in the next big update
