### ISSUE TITLE
Settings Customiser not working with everything.

### ISSUE THREAD

**Issue by AveR4g3** [leminlimez/Cowabunga#236]
Hi,
Please keep up with the good work!
I've noticed that the new way to customise settings labels does not work completely. Removing the labels works fine with almost anything, but not with Wi-Fi, VPN, Sounds and Haptics, Focus, Touch ID and Passcode, Wallet & Apple Pay, Passwords, and finally, TV. It is good when it still displays the labels on the applications, but these ones do not get affected by it, and I think they should.

Thanks in advance!

Edit: The same thing happened with removing the icons, except that this time only VPN, Touch ID & Passcode, and Wallet & Apple pay did not work.

iPhone10,4 (iPhone 8(GSM)),
iOS 15.4.1,
Cowabunga v. 10.00.0

**Comment by Boos4721** [comment]
same here

**Comment by leminlimez** [comment]
this cant be fixed, there are some stuff that do not have a cache value
