### ISSUE TITLE
Springboard colors not working (10.0.0)

### ISSUE THREAD

**Issue by ICARUS-2** [leminlimez/Cowabunga#242]
Anytime I apply a springboard color in the latest version, no matter the selected color, always turns the affected module black.
Have tried this with:
- Dock
- CC module BG
- App switcher
- Notification Banner BG

Device is A14 12PM / iOS 16.1.1

This issue did not occur prior to version 10 (Have used versions 8.12, 8.13, 8.14)

**Comment by leminlimez** [comment]
fixed
