### ISSUE TITLE
CC Background Blur/Folder Blur malfunction v10.0.X

### ISSUE THREAD

**Issue by ICARUS-2** [leminlimez/Cowabunga#244]
When setting the CC background blur or the folder blur, the amount of blur applied always seems to be maxed out regardless of whether the Blur slider is set to 0 or 150.

In the image below, the blur meter has been set to zero (but enabled), but the background appears as if I maxed out the slider.

![IMG_7342](https://user-images.githubusercontent.com/60612247/227604095-afadba86-87a3-40b2-a740-379a3c7a4690.PNG)

Issue occurs on versions 10.0.0 and 10.0.1.
Device: A14 12 Pro Max, 16.1.1

**Comment by leminlimez** [comment]
this is not the blur, it is the opacity
just lower the opacity in the color picker

**Comment by ICARUS-2** [comment]
> this is not the blur, it is the opacity just lower the opacity in the color picker

My apologies, thank you for the clarification
