### ISSUE TITLE
Unable to restore to default from dynamic island

### ISSUE THREAD

**Issue by ABreadTree** [leminlimez/Cowabunga#27]
![image](https://user-images.githubusercontent.com/62497798/212462350-ba7c5b08-06cc-4ccc-899a-cdacd3f2c0bd.png)
 As pic shown, when you want to restore default setting, the dynamic island is still there and both opinions are triggered.

**Comment by ABreadTree** [comment]
iPhone 13 Pro w ios 16.1.2

**Comment by leminlimez** [comment]
Yeah this is part of the fix to prevent bootloops. You most likely had dynamic island enabled while updating. Delete the app, downgrade to v5.2.0, disable it, update, and then re-enable it.

**Comment by ABreadTree** [comment]
understood, cheers
