### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by GoldStriker99** [leminlimez/Cowabunga#28]
Would it be possible to add a toggle that would hide the text below widgets and apps on the home screen?

**Comment by Void48** [comment]
> Would it be possible to add a toggle that would hide the text below widgets and apps on the home screen?

ooh hiding the text below widgets would be awesome if it's possible 👍🏻

**Comment by Void48** [comment]
@leminlimez wouldn't it be better to edit the name of this issue?

**Comment by leminlimez** [comment]
this cannot be done without a jailbreak or without breaking functionality of multiple apps
