### ISSUE TITLE
Remove the pop-up

### ISSUE THREAD

**Issue by morduk1** [leminlimez/Cowabunga#297]
Hello, i I looked for the function to ask a question but I didn't find it, I would like to know about the possibility of removing this annoying message when using the ios beta version

> 
![erro ios 15](https://github.com/leminlimez/Cowabunga/assets/28366557/44f9c478-b543-4382-b6cb-07e12e99fcf5)

USING CAWABUNGA VIA TROLLBOX 
Iphone 12 pro
IOS 15.5 RC BETA 4 
thanks !

**Comment by leminlimez** [comment]
cannot be done
