### ISSUE TITLE
Not Working 16.1.2

### ISSUE THREAD

**Issue by XivuBestGirl** [leminlimez/Cowabunga#3]
I’ve sideloaded the app, but when I press “Apply and Respring”, nothing happens. Did I miss a step somewhere? Using AltStore on IOS 16.1.2

Update: Still doesn't seem to work on v4.0.0 (all features, not just the dock)

**Comment by AirOne-dev** [comment]
Same here on IOS 16.1.1

**Comment by Temporius** [comment]
The same iOS 15.1 (TrollStore)

**Comment by CobreDev** [comment]
Same here on my 16.1.2 iPhone 13 mini

**Comment by binnichtaktiv** [comment]
Same here

**Comment by leminlimez** [comment]
It is very inconsistent and I am not exactly sure what to do to fix it. I will continue looking though!

**Comment by binnichtaktiv** [comment]
> It is very inconsistent and I am not exactly sure what to do to fix it. I will continue looking though!

Thanks🙏🏻

**Comment by CobreDev** [comment]
I've figured out that if you hit "Apply without respring" and then respring using the App Library trick to respring, it'll work pretty much 100% of the time

**Comment by XivuBestGirl** [comment]
> I've figured out that if you hit "Apply without respring" and then respring using the App Library trick to respring, it'll work pretty much 100% of the time

"App Library trick"?

**Comment by CobreDev** [comment]
> "App Library trick"?

https://www.reddit.com/r/jailbreak/comments/1077vtx/comment/j3m6jiy/?utm_source=share&utm_medium=web2x&context=3

**Comment by XivuBestGirl** [comment]
Thank you! It really does work!

**Comment by MJG604** [comment]
> I've figured out that if you hit "Apply without respring" and then respring using the App Library trick to respring, it'll work pretty much 100% of the time

This does not work for me on iPhone 14 pro max iOS 16.1.2 I've tried many many times and nothing seems to work I can't apply any of the tweaks.

**Comment by MJG604** [comment]
> I've figured out that if you hit "Apply without respring" and then respring using the App Library trick to respring, it'll work pretty much 100% of the time

This does not work for me on iPhone 14 pro max iOS 16.1.2 I've tried many many times with no success. I can't get any tweaks to apply.
