### ISSUE TITLE
hide the app labels with Cowabunga

### ISSUE THREAD

**Issue by aviv926** [leminlimez/Cowabunga#318]
Is this possible to hide the app labels with Cowabunga?

**Comment by leminlimez** [comment]
no

**Comment by aviv926** [comment]
> no

I actually just saw it
https://github.com/leminlimez/CowabungaLite

Note here that it has the Hide App Labels feature
it will not work?

**Comment by leminlimez** [comment]
that is because it creates webclips

**Comment by aviv926** [comment]
> that is because it creates webclips

Tried it now on my iphone 11 with ios 16.1 beta
And it didn't work for me
Do you know if it still works?
