### ISSUE TITLE
Hope the updated system can be used (iOS16.1.2 or above)

### ISSUE THREAD

**Issue by slacc8808** [leminlimez/Cowabunga#321]
I hope the developers can update the system as soon as possible. My iPhone14Pro has been updated to ios 16.3.1 when I bought it, so I am disappointed that I cannot use the program, so I request you to open source it as soon as possible!

**Comment by leminlimez** [comment]
cowabunga is already open source and cannot be updated for newer versions

**Comment by slacc8808** [comment]
Yes, I understand, I mean when will you update the version so that ios 16.3.1 can be installed directly on the phone, without relying on macos or win to enable it

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: leminlimez ***@***.***>
寄件日期: Sunday, July 16, 2023 2:20:42 AM
收件者: leminlimez/Cowabunga ***@***.***>
副本: slacc8808 ***@***.***>; Author ***@***.***>
主旨: Re: [leminlimez/Cowabunga] Hope the updated system can be used (iOS16.1.2 or above) (Issue #321)


cowabunga is already open source and cannot be updated for newer versions
