### ISSUE TITLE
[Feature Request] Fixing devices region different (like FaceTime for UAE devices or FaceTime Audio for CH/A devices)

### ISSUE THREAD

**Issue by 34306** [leminlimez/Cowabunga#39]
There is a tweak for jailbreak that support change to fix that.
Link: https://github.com/parrotgeek1/Globalize
Read around the source code, they just change the MobileGestalt.plist file 
In the /var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches/com.apple.MobileGestalt.plist to fix the problem.
We can cloning that tweak to generate then modify MobileGestalt but it takes me 2 day and I relise that it is too difficult to solve that. Hope you can check that and have a solution for this!
Thanks for your hardworking!

**Comment by leminlimez** [comment]
what is it changing in the plist?

**Comment by 34306** [comment]
I checked that changed whole the plist and some different (for example, it change KH/A to X/A, etc)

**Comment by leminlimez** [comment]
After trying a few different ways including the region/model like you suggested, I don't think it's possible

**Comment by 34306** [comment]
Got it, thanks!
