### ISSUE TITLE
v4.0.0 issue with new options

### ISSUE THREAD

**Issue by davidkh88** [leminlimez/Cowabunga#4]
Hide Dock and Hide Home Bar works great with this update but Disable Folder Blur partially works for several of minutes and then blur came back again. Please look into this. Thanks!

Reported from iOS 15.5 with 12 Pro Max.

**Comment by leminlimez** [comment]
I am currently looking into a method to make changes continually apply in the background to hopefully fix these issues.

**Comment by davidkh88** [comment]
doesn't doing like that could cause the battery drain? I am not sure with the process or the code you're writing, just my experience that anything that running in the background mostly drains the battery.

**Comment by davidkh88** [comment]
And v4.0.1 is working a bit weird, I turned all 3 top options except Disable Folder Blur at the bottom but all 3 never work at the same time. Hide Home Bar always works but if Hide Dock works, Hide Folder Background doesn't and if Hide Folder Background works, Hide Dock doesn't :/
