### ISSUE TITLE
 [Feature Request] Status Bar

### ISSUE THREAD

**Issue by jlbrkntr** [leminlimez/Cowabunga#40]
Would be nice to be able to hide status bar elements in iOS 16.

**Comment by leminlimez** [comment]
I believe it may be possible without needing to back up and restore but I need to do some more research

**Comment by jlbrkntr** [comment]
Wonderful, I'm mostly interested in iPadOS especially the hamburger menu that appears in the middle of the task bar when using certain apps (multitasking feature) and the time though I'm sure there are other elements people might be eager to hide too depending on what's technically possible.

**Comment by jlbrkntr** [comment]
Wonderful, I'm mostly interested in iPadOS especially the hamburger menu that appears in the middle of the status bar when using certain apps (multitasking feature) and the time though I'm sure there are other elements people might be eager to hide too depending on what's technically possible.

**Comment by leminlimez** [comment]
I do not have an iPad on iOS 15+ to look into where it is in the files unfortunately so I may not be able to

**Comment by jlbrkntr** [comment]
Yeah I think the hamburger menu in the middle of the status bar might be unique to iPadOS because they frequently highlight the multitasking features on the iPads. Maybe something can be done about hiding the clock though?
