### ISSUE TITLE
Issues with screen sizing and keyboard gaps and iPhone X gestures

### ISSUE THREAD

**Issue by minolazo** [leminlimez/Cowabunga#45]
![A969AC96-90F1-44B5-AF08-63307BA94428](https://user-images.githubusercontent.com/118779345/214456082-1e6a50fd-5909-4fad-9a8f-d9623353cb97.jpeg)

hey bro idk if anyone else has had this or these issues but if you can issue a fix or point me in the right direction to fix this I would appreciate you highly !!

Ok so first thing first since nobody ever seems to include this info , this issue was on a iPhone 8 iOS 15.6 non jailbroke 

I can’t seem to figure out why the iPhone X gestures setting resizes my screen in certain apps and my lock screen for sure if you notice the picture I included it shows you the displacement and you can barely see the lock screen flashlight and camera toggles also I have the classic gap at the bottom of my keyboard just like the little x cydia tweak used to do to my jailbroke phones which causes certain apps to be resized to the point where certain buttons become displaced or non able to be touched period …. My third and final issue/question is how can I toggle off the iPhone X gestures because when I go to the app and try to get it back to normal both of the options inside of the gesture section are selected and no matter if I click default and apply and respring it doesn’t change it I even went as far as restarting my whole phone after I applied and resprung it and I still have the same issue so basically I can’t turn off the iPhone X gestures at all 
![092CB5C4-FA9F-4C5A-A88C-F80045496D0E](https://user-images.githubusercontent.com/118779345/214463112-3a20f100-13fa-482f-bb50-49e0bf08342d.png)
![F72035E1-108A-4AAC-87D7-BF5790A072B1](https://user-images.githubusercontent.com/118779345/214463117-1b870f01-707b-40b7-ae3e-e0ba1526c614.png)
![FD778A17-7301-491E-BE39-2D69A9974D76](https://user-images.githubusercontent.com/118779345/214463120-0338d278-a16f-497e-b307-ee729f3fbd26.png)
 
 
… I hope I’ve included enough info for you to be able to understand my issues and thank you for creating this app in the first place I just need a lil help that’s all bro 💯

**Comment by leminlimez** [comment]
I am unable to do anything about the resizing because it requires a jailbreak. The default subtype is an issue if u deleted app data without setting back to default.

I will need to find the iphone 8 default subtype number and add a reset subtype button tomorrow

**Comment by minolazo** [comment]
> I am unable to do anything about the resizing because it requires a jailbreak. The default subtype is an issue if u deleted app data without setting back to default.
> 
> I will need to find the iphone 8 default subtype number and add a reset subtype button tomorrow

I did what you said about setting it back to default before the update and I still faced that issue bro no hard feelings just thought I’d let you know

**Comment by leminlimez** [comment]
I added a reset button in the latest release v6.1.3, hope that helps!
