### ISSUE TITLE
Failed to apply some custom audio

### ISSUE THREAD

**Issue by latiefahmad** [leminlimez/Cowabunga#46]
If I switch Camera Sound (Begin Recording and End Recording) to off, I was get pop up with Failed to apply some custom audio.
and Carier name doesnt work too
ip8 16.1.2

**Comment by minolazo** [comment]
I’m not sure if you know or not but the sound you import also has to be a .caf file or it won’t work

**Comment by leminlimez** [comment]
Sorry, I misread the issue. Turns out I made a typo in the file path, will be fixed later today in v6.1.3.
