### ISSUE TITLE
Can you add "Passcode faces" from TrollTools?

### ISSUE THREAD

**Issue by Radiicall** [leminlimez/Cowabunga#48]
It would be very appreciated if you could add this to your app. Free developer accounts are not great to work with...

![IMG_A4381679CBC2-1](https://user-images.githubusercontent.com/66682497/214691169-e92ed18e-435a-4b3c-91aa-0f60b4db1224.jpeg)

**Comment by leminlimez** [comment]
I tried. Not possible, MDC cannot edit those caches

**Comment by Radiicall** [comment]
hmm that's a shame, thanks for the quick answer!

**Comment by leminlimez** [comment]
new discoveries have been made! this will most likely come next update!

**Comment by leminlimez** [comment]
Added!
