### ISSUE TITLE
Feedback for ordinary users like me

### ISSUE THREAD

**Issue by Alectrochess** [leminlimez/Cowabunga#51]
Saya bukan develover saya juga bukan seorang programer tapi saya sangat suka dengan Cowabunga ini
Masukan saya, saya harap layar untuk iphone 8 plus bisa menyesuaikan resolusinya dan untuk keyboard juga bisa di sesuaikan
Untuk fitur iphone x gestures
Termakasih untuk semua develover yang sudah menciptakan aplikasi ini
![284B749A-373D-4097-AAE8-34E20E8E75F1](https://user-images.githubusercontent.com/123652808/214877536-87f460f1-e164-4c11-b6bd-e532973c8b04.png)
![CB66F995-D425-4D88-ADB3-8E29C7077102](https://user-images.githubusercontent.com/123652808/214877586-2963bec5-0034-4519-a72c-6d3e51149a6b.png)

**Comment by leminlimez** [comment]
Tidak mungkin tanpa jailbreak
