### ISSUE TITLE
The new “Carrier name” feature is not working

### ISSUE THREAD

**Issue by suprewing007** [leminlimez/Cowabunga#52]
Whenever I change the Carrier name using the “Carrier Name” feature it tells me to reboot, but I’ve rebooted my iPhone and the carrier was still the same.

iPhone X 
iOS 16.1.1
Cowbunga v6.1.3

**Comment by suprewing007** [comment]
> Whenever I change the Carrier name using the “Carrier Name” feature it tells me to reboot, but I’ve rebooted my iPhone and the carrier was still the same.
> 
> iPhone X iOS 16.1.1 Cowbunga v6.1.3

**Comment by leminlimez** [comment]
carrier changer will not work with every carrier
