### ISSUE TITLE
Does Not Disable Shortcut Banner

### ISSUE THREAD

**Issue by FrenchToucan** [leminlimez/Cowabunga#53]
Using v6.1.4 on iOS 15.4.1. Everything seems to work EXCEPT Shortcut banner disabling. When I open a shortcut, the banner still displays.

**Comment by leminlimez** [comment]
Doesn't work on ios 15. With the new method, I will see if I can add it a different way in the next update

**Comment by leminlimez** [comment]
now have a fix for it using a new method, coming next update
