### ISSUE TITLE
Extra preferences crash

### ISSUE THREAD

**Issue by Radiicall** [leminlimez/Cowabunga#56]
Enabling extra preferences causes "Photos" tab in settings to crash on open, tried several resprings. iOS 16.0.0 iPhone 13 Pro

**Comment by leminlimez** [comment]
seems to have an issue for ios 16 users, I will look into it

**Comment by Nigel1992** [comment]
Working for me on iOS 16.1.2
Maybe I can help somehow ?

**Comment by Radiicall** [comment]
It's working as of v7.0.1
