### ISSUE TITLE
Crashed after applying career name

### ISSUE THREAD

**Issue by Gluki0** [leminlimez/Cowabunga#57]
iPhone XS Max, 15.6(19G69)
Install via dev certificate

**Comment by Gluki0** [comment]
Also, the items in the SpringBoard Tools menu and in Audio Changer don’t work

**Comment by leminlimez** [comment]
i will look into the carrier crash
the dock does reset when changing themes and wallpapers, i cant do anything about that
turn on location and background applying and reopen the app after respring, it will keep the audio applied

**Comment by andrwmai** [comment]
Same result here. After applying the app just crashes. Also a reboot doesn't change the carrier either even though before applying the prompt says to reboot to apply.

**Comment by mehapps** [comment]
Ive been seeing this too, iPhone 14 Pro Max and iOS 16.1.1

**Comment by leminlimez** [comment]
you should all revert back to v6.1.4 while i look into this
idk why it is impacting things that i didnt change

**Comment by mehapps** [comment]
Reverted to v6.1.4, still crashing

**Comment by leminlimez** [comment]
idk what is causing it, i need to investigate further

**Comment by andrwmai** [comment]
@leminlimez just tried on 7.0.2 and it still crashes after applying.
