### ISSUE TITLE
App wont open. Crashing

### ISSUE THREAD

**Issue by Amachik** [leminlimez/Cowabunga#60]
iOS 14.5.1
iPhone 8
Jailbreaked with checkra1n(Odyssera1n)
Installed trollstore.

_HI, i installed ur app with trollstore but it is crashing upon launch. latest working version is 6.1.4_. **7.0.0, 7.0.1, will crash**

**Comment by leminlimez** [comment]
I found a fix to the crash on versions prior to 15.4, coming soon

**Comment by leminlimez** [comment]
fixed
