### ISSUE TITLE
Selecting Enable for Extra Preferences causes error

### ISSUE THREAD

**Issue by kharder69** [leminlimez/Cowabunga#65]
Selecting enable for Extra Preferences causes error message.
![33383316-9616-4236-87BB-5D42C69CDDE0](https://user-images.githubusercontent.com/17145280/215278274-813a74d1-0bb5-4efa-a8b0-26f9450ec271.png)

**Comment by kharder69** [comment]
I am using an iPad Air 5 with 16.1.1.

**Comment by Radiicall** [comment]
Did you try with 7.0.0? The newest 7.0.1 uses the "Phone" tab in settings and I dont think that exists on iPadOS

**Comment by leminlimez** [comment]
hopefully fixed

**Comment by kharder69** [comment]
> hopefully fixed

Not fixed, does not work on 16.1.1 on iPad.
