### ISSUE TITLE
Error when selecting Passcode Faces

### ISSUE THREAD

**Issue by kharder69** [leminlimez/Cowabunga#66]
Whenever I select Passcode Faces I get the following error.  I have tried reset faces multiple times and this does not resolve the problem.
![312D5469-FE46-4024-94F3-769AE283F79E](https://user-images.githubusercontent.com/17145280/215278352-fa20232c-3909-45ce-ab53-045cf5b4dc63.png)

**Comment by kharder69** [comment]
I am using an iPad Air 5 with 16.1.1.

**Comment by leminlimez** [comment]
when resetting faces, you need to go to the passcode screen
