### ISSUE TITLE
Add Dock Transparent tweak

### ISSUE THREAD

**Issue by kharder69** [leminlimez/Cowabunga#68]
Was wondering if it is possible to add the transparent dock tweak to the app.  The transparent dock app that I have does not remain active and keeps reverting back to non-transparent.

**Comment by leminlimez** [comment]
1. not a jailbreak so there is no tweak injection
2. enable running in background, it keeps the dock hidden

**Comment by kharder69** [comment]
Not sure I understand your answer for number 1 as it does work and makes dock transparent but doesn't remain transparent.

**Comment by leminlimez** [comment]
oh, ignore answer 1 then, just follow answer 2
