### ISSUE TITLE
Hide Rotation Lock Icon (iPhone's with home button models)

### ISSUE THREAD

**Issue by yusuf0142** [leminlimez/Cowabunga#73]
Could there be any way to hide the rotation lock icon on iphone models with a home button?

**Comment by leminlimez** [comment]
in the control center?

**Comment by tkiengarrixer** [comment]
Maybe status bar

**Comment by yusuf0142** [comment]
Yes in the status bar, it looks really annoying. Could this be possible? Thanks in regards.. For the iPhones with a home button, without a notch you know.

**Comment by leminlimez** [comment]
It shouldn't be too difficult. I already found the assets file of many of the status bar elements so it's probably there

**Comment by yusuf0142** [comment]
Thanks a lot! I mean it!

**Comment by leminlimez** [comment]
forgot to mention it is coming in tomorrow's update

**Comment by yusuf0142** [comment]
Thank you!! There was another new app called StatusMagic, which done it already, but still thanks a lot!
