### ISSUE TITLE
SB and audio changes not working on 16.1.2

### ISSUE THREAD

**Issue by afastaudir8** [leminlimez/Cowabunga#76]
I deloyOTAed from 15.6 to 16.1.2 and used a backup taken on 16.2b3. Audio and SB things won’t apply no natter how many times I press the Apply button and respring.

**Comment by leminlimez** [comment]
Can you try [v6.1.4](https://github.com/leminlimez/Cowabunga/releases/tag/v6.1.4) and see if they work in that version?

I think something might have happened when escaping sandbox with v7.0.0 but I'm not sure

**Comment by afastaudir8** [comment]
It didn’t work on 6.1.4 either

**Comment by afastaudir8** [comment]
I got an audio tweak to apply! SB tweaks still don’t seem to work though

**Comment by leminlimez** [comment]
try tapping apply with respring off and then respring using the app library method

**Comment by afastaudir8** [comment]
The App Library method worked!
