### ISSUE TITLE
Error: Optional(“Can\'t patchfind.”)

### ISSUE THREAD

**Issue by RextyIsAlive** [leminlimez/Cowabunga#77]
I downloaded with esign.

**Comment by Nigel1992** [comment]
Unrelated question: Where did you download esign from?
Looks like an interesting tool.

**Comment by leminlimez** [comment]
its possible that it could be an esign issue, but I can't fix this

**Comment by Nigel1992** [comment]
What's your discord @RextyIsAlive ?
