### ISSUE TITLE
Tweaks barley work

### ISSUE THREAD

**Issue by stossy11** [leminlimez/Cowabunga#84]
So I am on iOS 16.1 iPhone 12 Pro
most the tweaks only work some of the time or don’t work at all

**Comment by leminlimez** [comment]
wait for the next update, we are changing a lot in the backend to hopefully work better

**Comment by Kief5555** [comment]
Same issue, carrier name don't work, I set and apply but it just crashes, I reboot phone and nothing apples.

Cowbunga@latest
Ios@16.1.2

**Comment by leminlimez** [comment]
for the carrier, it is hit or miss. we might have found a new way of changing it that works 100% of the time without a reboot, coming soon

**Comment by Kief5555** [comment]
> for the carrier, it is hit or miss. we might have found a new way of changing it that works 100% of the time without a reboot, coming soon

Can you build a copy? My Xcode too out of date lol

**Comment by Kief5555** [comment]
Oh yeah, extra settings don't work

**Comment by leminlimez** [comment]
> > for the carrier, it is hit or miss. we might have found a new way of changing it that works 100% of the time without a reboot, coming soon
> 
> Can you build a copy? My Xcode too out of date lol

it has not been fully implemented yet

**Comment by leminlimez** [comment]
try the latest update v7.0.3, it improves reliability a lot with the new respring method

**Comment by Kief5555** [comment]
> try the latest update v7.0.3, it improves reliability a lot with the new respring method

I'm out of app ids. But I grabbed 7.1.0 beta 4

**Comment by stossy11** [comment]
> for the carrier, it is hit or miss. we might have found a new way of changing it that works 100% of the time without a reboot, coming soon

It worked fine every time for me that and the password icon was the only one that works properly

**Comment by stossy11** [comment]
I have updated but now the audio tab is greyed out

**Comment by leminlimez** [comment]
fixed audio tab in v7.0.4, idk why it happened but its fixed now
