### ISSUE TITLE
Error when selecting enable for Extra Features

### ISSUE THREAD

**Issue by kharder69** [leminlimez/Cowabunga#88]
Running tweak on iPad 16.1.1. Appears this issue has not been resolved yet, but was closed previously.
![image](https://user-images.githubusercontent.com/17145280/216351709-843eff5b-3ec5-4a22-8d54-9efbb3074cb0.png)

**Comment by leminlimez** [comment]
oops sorry, i am looking into a different way of doing it in the next update that should hopefully be a lot better

**Comment by kharder69** [comment]
> oops sorry, i am looking into a different way of doing it in the next update that should hopefully be a lot better

Still not working on my iPad.

**Comment by leminlimez** [comment]
The features are being implemented into cowabunga's main app without the need to enable extra settings
