### ISSUE TITLE
remove device subtype

### ISSUE THREAD

**Issue by summerdxfvsdrf** [leminlimez/Cowabunga#89]
i cant seem to disable the ip x gestures.i want to go back to the default one but i cant i already tried to uninstall it and restarted my device but noyhing chnage.please help

**Comment by leminlimez** [comment]
tap the "reset default subtype" button

**Comment by summerdxfvsdrf** [comment]
Hello i already type the remove subtype but it says send issue to github.I
can't go back to remove the gestures.

**Comment by leminlimez** [comment]
what is your device?

**Comment by summerdxfvsdrf** [comment]
I have iphone 6splus ios ver 15.7.1

**Comment by summerdxfvsdrf** [comment]
The icons on the lockscreen are zoomed to the edges too.😿

**Comment by leminlimez** [comment]
added your phone model, please reset default subtype again

**Comment by summerdxfvsdrf** [comment]
I tried it still doesn't work😭😥.How can i remove the gestures?

**Comment by leminlimez** [comment]
i apologize, i made a typo

please reset the default subtype one last time

**Comment by summerdxfvsdrf** [comment]
😿

**Comment by summerdxfvsdrf** [comment]
It's still the same😿

**Comment by leminlimez** [comment]
did it say u still needed to make an issue?

if it said success then go back to the device subtypes, set it back to default, then respring

**Comment by summerdxfvsdrf** [comment]
It said failed to determine default subtype and send an issue

**Comment by leminlimez** [comment]
iphone 6s plus?

**Comment by summerdxfvsdrf** [comment]
Yes, it is.

**Comment by leminlimez** [comment]
can you say the model number that shows in settings?

**Comment by summerdxfvsdrf** [comment]
MKTV2LL/A

**Comment by leminlimez** [comment]
odd, resetting the subtype should work as long as you are connected to wifi

you may need to change it yourself in a file manager
go to /var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches
open com.apple.MobileGestalt.plist and look for the property **ArtworkDeviceSubType**
change that property to 570, save, and respring

**Comment by leminlimez** [comment]
update: i have found the issue and i am working to fix it

**Comment by Naseem0547** [comment]
Hi

**Comment by leminlimez** [comment]
does the newest update work?
