### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by baimour** [leminlimez/Cowabunga#9]
![iShot_2023-01-09_01 48 30](https://user-images.githubusercontent.com/85350961/211211122-815538bd-cbb0-4414-b9f3-088d7bf8578f.png)

**Comment by leminlimez** [comment]
are you on an intel mac? this is not really something I have control over as it is not my library

**Comment by baimour** [comment]
It seems so. Can it be solved?

**Comment by leminlimez** [comment]
You can actually delete the SantanderWrapper dependencies since I no longer use them. Deleting should solve the issue
