### ISSUE TITLE
Red bar on the top of status bar on iphone 8 , iphone x gestures

### ISSUE THREAD

**Issue by XAhad32** [leminlimez/Cowabunga#90]
whenever I apply iphone x gestures on iphone 8 , I get to see a red bar on the top of status bar. can this be fixed?

**Comment by leminlimez** [comment]
the only fix for now is to set the resolution to the iphone x resolution

**Comment by XAhad32** [comment]
> the only fix for now is to set the resolution to the iphone x resolution

Cool , ill try that out. Thanks!!

**Comment by XAhad32** [comment]
and one more thing , should I close this issue? or will that be worked on later in future?

**Comment by leminlimez** [comment]
it will be worked on but i'm not sure how long it will take

right now we are focused on a huge new feature coming next update
