### ISSUE TITLE
Failed to determine Device Default Subtype

### ISSUE THREAD

**Issue by Mjevia** [leminlimez/Cowabunga#91]
There is a problem that i encountered and that is when I try to reset my Device Subtype there is an error I hope you take action on this! Thank youu

**Comment by leminlimez** [comment]
what device?

**Comment by Mjevia** [comment]
Iphone 6s Plus

**Comment by leminlimez** [comment]
idk why that phone can't determine the subtype but i may have to reprogram the button

you may need to change it yourself in a file manager for now
go to /var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches
open com.apple.MobileGestalt.plist and look for the property ArtworkDeviceSubType
change that property to 570, save, and respring

**Comment by Mjevia** [comment]
What file manager should I use?

**Comment by Yan-Jobs** [comment]
Use [this](https://github.com/mineek/SantanderMacDirtyCow/actions/runs/3920286280)

**Comment by BKalwoda** [comment]
I changed the value to 2436 and not to 570. With 2436 it worked for me (iPhone 6s).
