### ISSUE TITLE
Failed to determine Default SubType

### ISSUE THREAD

**Issue by Panak252** [leminlimez/Cowabunga#96]
iPhone 7 Plus, iOS 15.6.1, unjailbroken.
Using most recent Cowabunga version (7.0.4), haven't used any other MacDirtyCow apps.

I set the device subtype to iPhone X Gestures, and then did a respring. After a few hours, the home button stopped waking up the phone, and so wanted to revert it to try again, but it runs into failures.

![image](https://user-images.githubusercontent.com/88540067/216808490-90bdd11f-7452-467b-9a25-c11803cb8ff3.png)

![image](https://user-images.githubusercontent.com/88540067/216808496-51f346dd-ab36-4f72-889e-d0eafabc7243.png)

The default SubType on another iPhone 7 Plus (15.3.1) is 570.

Perhaps a way to set the default device SubType could be implemented? Or a list of SubTypes to choose from?
Thanks :)

**Comment by leminlimez** [comment]
i might have made a mistake in the code and it is having issues getting the subtype

for now you may need to try my response to #89

**Comment by leminlimez** [comment]
i have found the issue, i am working to try to fix it

**Comment by Panak252** [comment]
Thank you for being so quick to respond, and thanks for notifying me about
it.
Take your time, and sorry for being late to respond, I don't look at my
mail every day.
Good debugging :)
